---
title: "Regress Rangers"
date: "15 April 2023"
date-modified: "`r Sys.Date()`"
number-sections: true
format: html
execute: 
  echo: true
  eval: true
  warning: false
editor: visual
---

# Welcome to our IS415 Project

We are RegressRangers, the team behind this project, and we are excited to share it with you. Our project focuses on exploring and visualizing geospatial data using the latest tools and technologies

## About the Project

Our goal is to create a comprehensive and user-friendly platform for exploring geospatial data. We believe that this information can be incredibly valuable for a wide range of applications, from urban planning to environmental monitoring. We will be specifically focusing on Geographically Weighted Regression Models.

To achieve this goal, we are using a variety of open-source tools and technologies, including [sf](https://r-spatial.github.io/sf/) for data processing, [Leaflet](https://leafletjs.com/) for interactive maps, and [Quarto](https://quarto.org/) for documentation and analysis.

## Meet the Team

Our team consists of Year 2 and 3 students from Singapore Management University. We bring a diverse range of skills and perspectives to the project, and we are committed to delivering high-quality and impactful results.

-   Peng You Yun

-   Ho Yong Quan

-   S Guganesh

## Get Started

To get started, please explore the links in the navigation menu above. We hope you enjoy our project and find it useful for your own work and interests.

Thank you for your support!

## Acknowledgement

We would like to thank Professor Kam Tin Seong for his guidance during this course. We wouldn't have been able to create this without him 😃
